### ISSUE TITLE
Lux not working

### ISSUE THREAD

**Issue by LazerusKI** [TheDrunkMafia/ThaumicInfusion#23]
The border shows up, but nearby blocks (F7) still show that it is dark.

**Comment by TheDrunkMafia** [comment]
Can you take a screenshot of what you are talking about?

**Comment by Alaberti** [comment]
Right-clicking the block with an empty hand to force a block update made it work for me.

**Comment by LazerusKI** [comment]
I will try that later then (currently at school)

**Comment by LazerusKI** [comment]
There you go.
After clicking once - it stays dark
http://i1331.photobucket.com/albums/w585/LazerusKI/Minecraft/1_zps0gddhetu.png
Clicking again (removing it) - it lights up
http://i1331.photobucket.com/albums/w585/LazerusKI/Minecraft/2_zpsclapzgia.png

**Comment by TheDrunkMafia** [comment]
Removing it causes the block to update cliently before the data for the effect is removed, just break/place a block near it and it will update.

**Comment by dirtyfargo** [comment]
I am having this issue as well, and I am aware that a block update will fix my issue. However, it seems I am having to re-apply a block update every time I re-log onto my server, or anytime I leave the loaded chunks and return, in order for the area to visually become re-lit up again client side.

**Comment by TheDrunkMafia** [comment]
Yeah, I know of this issue. It is a problem with the updating of the blocks rendering when the server syncs the data to the client, this issue is only apparent on servers and not clients. Which is why its taken me some time to find this issue, as the client one is what I fixed.

**Comment by dirtyfargo** [comment]
Ah alright, thanks :) Just wanted to make sure the issue was known!

**Comment by TheDrunkMafia** [comment]
Its been fixed and I've released a new version of the mod: http://minecraft.curseforge.com/mc-mods/220308-thaumic-infusion

**Comment by dirtyfargo** [comment]
Awesome, thank you :) I'll push the update to my private modpack / server as soon as possible to test it out.

**Comment by dirtyfargo** [comment]
I am still having the issue on Thaumic Infusion 4.07. On server, when I leave loaded chunks and return, spaces infused with Lux have disappeared.
Forge Version: 10.13.4.1470

**Comment by TheDrunkMafia** [comment]
This is not got anything to do with Lux not updating, this is another issue with world saving.
